# Generated by Django 5.0 on 2023-12-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studen',
            new_name='Student',
        ),
    ]
